name: 'Run Ecspresso'
description: 'Run ECS task with Ecspresso'
author: hello@cloudposse.com
branding:
  icon: 'search'
  color: 'white'
inputs:
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
  region:
    description: AWS Region
    required: true
  cluster:
    description: Cluster name
    required: true
  ecspresso-version:
    description: Ecspresso version
    required: false
    default: v2.1.0
  application:
    description: Application name
    required: true
  taskdef-path:
    description: Task definition path
    required: true
  timeout:
    description: Ecspresso timeout
    required: false
    default: 5m
  overrides:
    description: A list of container overrides in JSON format that specify the name of a container in the specified task definition and the overrides it should receive.
    required: false
    default: "{}"

outputs:
  webapp-url:
    description: "Web Application url"
    value: 'null'
          # https://${{ steps.webapp.outputs.output }}


runs:
  using: "composite"
  steps:
    - uses: 1arp/create-a-file-action@0.2
      with:
        path: './'
        file: 'overrides.json'
        content: |
          ${{ inputs.overrides }}

    - name: Schema path
      id: schema
      shell: bash
      run: |
        echo "path=${GITHUB_ACTION_PATH}/schema/run-task-override.schema.json" >> $GITHUB_OUTPUT

    - name: Validate task override
      uses: cardinalby/schema-validator-action@v3
      with:
        file: ./overrides.json
        schema: ${{ steps.schema.outputs.path }}

    - name: 'Install jq 1.6'
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: 1.6
        force: 'true'

    - uses: kayac/ecspresso@v2
      with:
        version: ${{ inputs.ecspresso-version }}

    - name: Set random environment variables
      uses: joellefkowitz/random-env@v1.0.0
      with:
        names: |
          TMP_DIR_NAME

    - name: Create TMP dir
      shell: bash
      run: |
        mkdir /tmp/${{ env.TMP_DIR_NAME }}

    - name: Init
      shell: bash
      run: |
        ecspresso init \
          --cluster=${{ inputs.cluster }} \
          --service=${{ inputs.application }} \
          --task-definition-path=/tmp/${{ env.TMP_DIR_NAME }}/ecs-task-def.json \
          --service-definition-path=/tmp/${{ env.TMP_DIR_NAME }}/ecs-service-def.json \
          --config-file-path=/tmp/${{ env.TMP_DIR_NAME }}/
      env:
        AWS_REGION: ${{ inputs.region }}

    - uses: 1arp/create-a-file-action@0.2
      with:
        path: './'
        file: 'ecspresso.yml'
        content: |
          region: ${{ inputs.region }}
          cluster: ${{ inputs.cluster }}
          service: ${{ inputs.application }}
          service_definition: /tmp/${{ env.TMP_DIR_NAME }}/ecs-service-def.json
          task_definition: ${{ inputs.taskdef-path }}
          timeout: ${{ inputs.timeout }}

    - name: Run
      shell: bash
      run: |
        ecspresso --config=./ecspresso.yml run --overrides-file=./overrides.json
      env:
        IMAGE: ${{ inputs.image }}:${{ inputs.image-tag }}
        AWS_REGION: ${{ inputs.region }}